/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OrderLaxyImport } fr./routes/order.laxyrder.laxy'

// Create/Update Routes

const OrderLaxyRoute = OrderLaxyImport.update({
  path: '/order/laxy',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order/laxy': {
      id: '/order/laxy'
      path: '/order/laxy'
      fullPath: '/order/laxy'
      preLoaderRoute: typeof OrderLaxyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/order/laxy': typeof OrderLaxyRoute
}

export interface FileRoutesByTo {
  '/order/laxy': typeof OrderLaxyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/order/laxy': typeof OrderLaxyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/order/laxy'
  fileRoutesByTo: FileRoutesByTo
  to: '/order/laxy'
  id: '__root__' | '/order/laxy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  OrderLaxyRoute: typeof OrderLaxyRoute
}

const rootRouteChildren: RootRouteChildren = {
  OrderLaxyRoute: OrderLaxyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/order/laxy"
      ]
    },
    "/order/laxy": {
      "filePath": "order.laxy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
